name: Terraform Apply

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  terraform-apply:
    runs-on: ubuntu-latest
    environment: dev

    defaults:
      run:
        working-directory: environments/dev

    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials with OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::442999092835:role/github-terraform-secure-platform-role
          aws-region: us-east-1

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_wrapper: false

      - name: Terraform init
        run: terraform init

      - name: Terraform plan
        run: terraform plan -out=tfplan

      - name: Install OPA
        run: |
          curl -L -o /tmp/opa https://openpolicyagent.org/downloads/v0.68.0/opa_linux_amd64_static
          chmod +x /tmp/opa
          sudo mv /tmp/opa /usr/local/bin/opa
          opa version

      - name: Run OPA policies
        run: |
          terraform show -json tfplan > tfplan.json
          opa eval --fail-defined --format pretty --data ../../policies/opa --input tfplan.json 'data.terraform.security.deny[_]'

      - name: Terraform apply
        run: terraform apply -auto-approve tfplan
